In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df=pd.read_csv('Database2.csv')
df1=pd.read_csv('datasetB.csv')

In [18]:
df.head()

  team_id         team department
0      T1  AccountCare    Service
1      T2  BillingHelp    Service
2      T3   AppSupport  Technical
3      T4   DeviceHelp  Technical

In [20]:
df1.head

<bound method NDFrame.head of     ticket_id month team_id channel  resolution_hours  satisfaction
0           1   Jan      T1   Email                12             4
1           2   Jan      T2    Chat                28             3
2           3   Jan      T3   Phone                36             2
3           4   Jan      T4   Email                20             4
4           5   Feb      T1    Chat                 8             5
5           6   Feb      T2   Phone                30             3
6           7   Feb      T3   Email                18             4
7           8   Feb      T4    Chat                40             2
8           9   Mar      T1   Phone                16             4
9          10   Mar      T2   Email                22             4
10         11   Mar      T3    Chat                32             3
11         12   Mar      T4   Phone                24             5
12         12   Mar      T4   Phone                24             5>

In [17]:
df.info()
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   team_id     4 non-null      str
 1   team        4 non-null      str
 2   department  4 non-null      str
dtypes: str(3)
memory usage: 228.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ticket_id         13 non-null     int64
 1   month             13 non-null     str
 2   team_id           13 non-null     str
 3   channel           13 non-null     str
 4   resolution_hours  13 non-null     int64
 5   satisfaction      13 non-null     int64
dtypes: int64(3), str(3)
memory usage: 756.0 bytes

In [14]:

df1.describe()

       ticket_id  resolution_hours  satisfaction
count  13.000000         13.000000     13.000000
mean    6.923077         23.846154      3.692308
std     3.774068          9.290193      1.031553
min     1.000000          8.000000      2.000000
25%     4.000000         18.000000      3.000000
50%     7.000000         24.000000      4.000000
75%    10.000000         30.000000      4.000000
max    12.000000         40.000000      5.000000

In [16]:
df1.isnull().sum()

ticket_id           0
month               0
team_id             0
channel             0
resolution_hours    0
satisfaction        0
dtype: int64

In [22]:
df1.isnull().duplicated()

0     False
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
dtype: bool